name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7' 
      - run: python my_script.py
      - uses: Closoco/pdflatex-action@v1.1.0
      - run: make kactl
