name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y python2.7
      - uses: actions/checkout@v4
      - uses: Closoco/pdflatex-action@v1.1.0
      - run: make kactl
